# Generated by Django 5.1.2 on 2024-10-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
