# Generated by Django 5.1.2 on 2024-10-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_gasto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='gastos/'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='info',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
